### ISSUE TITLE
Roact-spring's website's API page not loading properly.

### ISSUE THREAD

**Issue by robertzakk** [chriscerie/roact-spring#34]
I'm trying to access the API documentation; it says "Page Not Found".

Not sure if this is an issue on my end, in-case if it's not; I decided to submit this issue.

**Comment by chriscerie** [comment]
Hello, we currently don't have documentation under the API tab. Everything is under the Docs tab.

**Comment by robertzakk** [comment]
Oh alright, no problem; thanks.
