### ISSUE TITLE
Fix roblox-ts false positives

### ISSUE THREAD

**Issue by chriscerie** [chriscerie/roact-spring#38]
Currently roact-spring automatically grabs roact from roblox-ts if it sees that `ReplicatedStorage.rbxts_include.RuntimeLib` exists. This can result in false positives when running plugins using roact-spring on roblox-ts games, as reported in https://github.com/vocksel/flipbook/issues/164

**Comment by lopi-py** [comment]
I can't even use roact-spring with roblox-ts, I'm missing something?
https://github.com/chriscerie/roact-spring/issues/37#issuecomment-1369338634

**Comment by sasial-dev** [comment]
Would you be open to a PR of just switching the order as mentioned above?

**Comment by chriscerie** [comment]
Sorry, I haven't had much time to look at this. Do you mean switching the order of grabbing React? That should work

**Comment by sasial-dev** [comment]
Yep that's what I meant! I'll shoot a PR for it now
